# Site settings
title: Moshe Vayner
description: Engineer | Entrepreneur | Kubernaut | Pythonista | Gopher | Hardcore Potterhead & Star Wars Fan

# User settings
username: Moshe Vayner
user_description: Gooner âš½ï¸ | Hardcore Potterhead & Star Wars Fan</br>Atlanta, GA
user_title: EngineerğŸ‘¨ğŸ»â€ğŸ’» | Entrepreneur ğŸ’¡ | Kubernaut âˆ | Pythonista ğŸ | Gopher ğŸ¦« | Techstars Alum ğŸ‘¨ğŸ»â€ğŸ“
email: moshe@vayner.me
twitter_username: MosheVayner
github_username: moshevayner

# Google-analytics
google-analytics:
  id: "UA-159344299-1"

exclude: ["package.json", "src", "node_modules"]

theme: jekyll-theme-cayman
